### ISSUE TITLE
Build Issue: failing to run build workflow

### ISSUE THREAD

**Issue by mbeps** [mbeps/ringmaster-messaging#21]
Reasons:

- [ ] `Module not found: Can't resolve 'encoding'`
- [ ] `A Node.js API is used (process.turbopack at line: 14) which is not supported in the Edge Runtime`
- [ ] Missing env variables

**Comment by mbeps** [comment]
Adding this should fix the problem of missing env variables by making the variables available:

```yml
env:
  NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
  SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
  SUPABASE_REFERENCE_ID: ${{ secrets.SUPABASE_REFERENCE_ID }}
```
